feat: add `useRealPaths` back
thecodrr/fdir pull request #104
Opened 2024-07-30 10:53 UTC by SuperchupuDev

While working on `tinyglobby` I've noticed there is no way to disable `fdir` returning the real path of a symlink anymore, due to #81 silently removing support for it (even though the documentation still mentions the feature!).

This PR adds it back, inside an object parameter instead for better API design (see https://github.com/thecodrr/fdir/issues/83#issuecomment-1282787956). It defaults to `true` for backwards compatibility

Closes #103

2024-08-05 11:50 UTC, SuperchupuDev commented
hi @thecodrr, would you mind taking a look at this anytime soon? symlinks wont quite work in my library until this (or an equivalent solution) is merged

2024-08-05 15:01 UTC, thecodrr commented
Relevant commit: https://github.com/thecodrr/fdir/commit/cdb201f4f2c3afdf05f46e42894a8ef5836568a0

2024-08-05 15:16 UTC, SuperchupuDev commented
yes, that commit is what this PR aims to implement, but #81 removed the `withSymlinks` parameter that commit introduced. i can rename this pr to make that clearer

2024-08-05 15:18 UTC, thecodrr requested changes
Thank you so much for adding this back!

2024-08-05 15:18 UTC, thecodrr commented on src/api/functions/resolve-symlink.ts
> +  fs.stat(path, (error, stat) => {
Let's use `fs.lstat` here as well.

2024-08-05 15:18 UTC, thecodrr commented on src/api/functions/resolve-symlink.ts
> +    const stat = fs.statSync(path);
Let's use `lstatSync` here.

2024-08-05 15:18 UTC, thecodrr commented on src/api/functions/resolve-symlink.ts
> +  return options.useRealPaths ? resolveSymlinksWithRealPathsAsync : resolveSymlinksAsync;
Let's invert these checks to be more consistent.

```suggestion
  if (options.useRealPaths)
    return isSynchronous
        ? resolveSymlinksWithRealPathsSync
        : resolveSymlinksWithRealPathsAsync;
  return isSynchronous
    ? resolveSymlinksSync
    : resolveSymlinksAsync;
```

2024-08-05 15:31 UTC, SuperchupuDev commented
changing it to lstat makes this test fail as it's returning non-resolved symlinks
![image](https://github.com/user-attachments/assets/46acdfea-cd01-4c6e-9f6e-debfff6b786c)

2024-08-05 16:22 UTC, SuperchupuDev commented
@thecodrr i've reverted the `lstat` change, it makes behavior the same as if not using `withSymlinks` at all for some reason. not to worry though as it seems to work as intended with `stat`

2024-08-15 17:46 UTC, SuperchupuDev commented
@thecodrr is there anything blocking the PR?

2024-08-25 07:52 UTC, thecodrr commented
> @thecodrr i've reverted the lstat change, it makes behavior the same as if not using withSymlinks at all for some reason. not to worry though as it seems to work as intended with stat

I looked more into this and apparently, here's the correct way to go about this:

- When `resolvePaths` is `true`, we should use `realpath` and `stat`.
- When `resolvePaths` is `false`, we should use `lstat`.

`lstat` works directly on the symlink (i.e. it doesn't check if the symlink points to a file on disk) which is what we want when `resolvePaths` is `false`. Doing `lstat` on a dirent we "know" for sure isn't a symlink is just waste of resources.

Another thing I noticed while looking at this is that the tests checking for errors are just plain wrong (no idea why I added tests that way). They'll pass even if there's no error. Instead of testing for errors, let's just test the output and see if the symlink was resolved or not. That'll be more foolproof.

2024-08-25 08:01 UTC, merged